# Generated by Django 4.0.6 on 2022-08-01 00:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('nom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('sujet', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sujet')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact',
                'ordering': ['-created'],
            },
        ),
    ]
