# Generated by Django 4.1.1 on 2023-02-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='sujet',
        ),
    ]
