# Generated by Django 4.1.1 on 2023-03-01 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_contact_sujet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-updated'], 'verbose_name': 'Contact'},
        ),
    ]
