# Generated by Django 4.1.1 on 2023-03-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_specialite_user_specialite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='pourcentage',
            field=models.IntegerField(blank=True, choices=[(0, '50'), (1, '60'), (2, '80'), (3, '90')], default=0, null=True, verbose_name='Pourcentage'),
        ),
    ]
