# Generated by Django 4.1.1 on 2023-02-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='keywords',
        ),
    ]
